// Code generated by sqlc. DO NOT EDIT.

package dbchat

import (
	"time"
)

type Message struct {
	ID       int32     `json:"id"`
	Author   string    `json:"author"`
	Text     string    `json:"text"`
	Datetime time.Time `json:"datetime"`
}
